- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.tar.gz dest=/opt/apache-tomcat-8.5.9.tar.gz

- name: Extract archive
  command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-8.5.9.tar.gz -C /opt/ creates=/opt/apache-tomcat-8.5.9 --strip-components=1

- name: chgrp directory
  command: chgrp -R tomcat /opt/apache-tomcat-8.5.9
  become: True
  become_method: sudo

- name: chmod tomcat directory
  command: chmod -R g+r /opt/apache-tomcat-8.5.9/conf
  become: True
  become_method: sudo

- name: chmod g+x tomcat conf directory
  command: chmod g+x /opt/apache-tomcat-8.5.9/conf
  become: True
  become_method: sudo

- name: tomcat webapps diretory
  command: chown -R tomcat /opt/apache-tomcat-8.5.9/webapps/
  become: True
  become_method: sudo

- name: tomcat work temp and logs diretory
  command: chown -R tomcat /opt/apache-tomcat-8.5.9/work/ /opt/apache-tomcat-8.5.9/temp/ /opt/apache-tomcat-8.5.9/logs/
  become: True
  become_method: sudo

- name: install directory
  file: src=/opt/apache-tomcat-8.5.9 path=/usr/share/tomcat state=link

- name: Change owner of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/
  notify: restart tomcat

- name: Configure Tomcat service
  template: src=tomcat.service dest=/etc/systemd/system/
  notify: restart tomcat

- name: systemctl daemon reload
  command: systemctl daemon-reload  
  become: True
  become_method: sudo

- name: systemctl start tomcat 
  command: systemctl start tomcat 
  become: True
  become_method: sudo

